version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend
      target: production
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src

networks:
  default:
    name: ideograph-network-prod
